[package]
name = "fsutil-memory"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
fsutil-core = { workspace = true }
tracing = { workspace = true }
orange-trees = "0.1"

[dev-dependencies]
pretty_assertions = "^1"
