[package]
name = "fsutil-core"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
log = { workspace = true }
thiserror = { workspace = true }
wildmatch = { workspace = true }

[dev-dependencies]
env_logger = "^0.11"
pretty_assertions = "^1"
tempfile = "^3"
